filetype off
set nocompatible
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'mileszs/ack.vim'
Bundle 'bronson/vim-trailing-whitespace'
Bundle 'eddsteel/vim-mail'
Bundle 'altercation/vim-colors-solarized'
Bundle 'Shougo/vimproc'
Bundle 'eagletmt/ghcmod-vim'
Bundle 'lungu/haskell.vim'
filetype plugin indent on

syntax on
set background=dark
colorscheme solarized

set shortmess=I
set hidden

set number
set numberwidth=4
set ruler
set modeline
set showcmd
set showmode

set nobackup
set directory=~/.vim/backup

set autoindent
set smartindent
set noexpandtab

set formatoptions+=tcroq
set textwidth=78
set nowrap

set ignorecase
set smartcase
set incsearch
set showmatch
set hlsearch

set backspace=indent,eol,start
set clipboard^=unnamed

set mouse=a
set scrolloff=3
set pastetoggle=<f12>

set lazyredraw
set ttyfast

set noerrorbells
set visualbell
set t_vb=

set spelllang=en,ru
nmap <silent> <F11> :set spell!<CR>
map! <silent> <F11> <ESC>:set spell!<CR>i

nmap <silent> <C-D> :NERDTreeToggle \| :silent NERDTreeMirror<CR>
map! <silent> <C-D> <ESC>:NERDTreeToggle \| :silent NERDTreeMirror<CR>

let g:NERDTreeIgnore=['\.o$', '\.d$', '\.hi$']

let g:haskell_indent_if=4
let g:haskell_indent_case=4

let g:mail_erase_quoted_sig=1
let g:mail_delete_empty_quoted=1
let g:mail_generate_abbrev=1
let g:mail_cursor_start=1

au FileType c,cpp call CHook()
function CHook()
    setlocal cindent
    setlocal cinoptions=:0,l1,g0,p4,t0,i4,+4,c1,(0,W4
endfunction

au FileType cabal call SetExpandTab(4)
au FileType haskell call SetExpandTab(4)

au FileType scheme call SchemeHook()
function SchemeHook()
    call SetExpandTab(2)
    setlocal lisp
    setlocal lispwords+=match,define-syntax,syntax-case,syntax-rules,define-type,type-case,define-core
endfunction

au FileType sh call SetExpandTab(4)
au FileType vim call SetExpandTab(4)
au FileType python call SetExpandTab(4)

au FileType text call SetExpandTab(2)
au FileType tex call SetExpandTab(2)

function SetExpandTab(width)
    setlocal expandtab
    let &l:tabstop=a:width
    let &l:shiftwidth=a:width
    let &l:softtabstop=a:width
endfunction

source ~/.vimrc.local
