syntax on
colorscheme desert256
filetype plugin indent on

set fileencodings=utf8,cp1251

set autoindent
set background=dark
set backspace=indent,eol,start
set clipboard^=unnamed
set formatoptions+=tqcro
set hidden
set ignorecase
set incsearch
set lazyredraw
set modeline
set mouse=a
set nobackup
set nocompatible
set noerrorbells
set noexpandtab
set nohlsearch
set noshowmatch
set noerrorbells
set visualbell
set nowrap
set pastetoggle=<f12>
set ruler
set scrolloff=3
set shortmess=I
set showcmd
set showmode
set smartcase
set smartindent
set smarttab
set spelllang=en,ru
set t_vb=
set textwidth=78
set ttyfast

let g:miniBufExplMapWindowNavVim=1 
let g:miniBufExplMapWindowNavArrows=1 
let g:miniBufExplMapCTabSwitchBufs=1 
let g:miniBufExplModSelTarget=1 
let g:miniBufExplMapCTabSwitchBufs=1
let g:miniBufExplUseSingleClick=1
let g:miniBufExplCloseOnSelect=1
let g:miniBufExplorerMoreThanOne=1000

let g:haskell_indent_if=4
let g:haskell_indent_case=4

map  <silent> <F11> :set spell!<CR>
map! <silent> <F11> <ESC>:set spell!<CR>i

nmap <silent> <C-D> :NERDTreeToggle \| :silent NERDTreeMirror<CR>
map! <silent> <C-D> <ESC>:NERDTreeToggle \| :silent NERDTreeMirror<CR>

nmap <silent> <C-B> :MiniBufExplorer<CR>
map! <silent> <C-B> <ESC>:MiniBufExplorer<CR>

au FileType c,cpp setlocal cindent
au FileType c,cpp setlocal cinoptions=:0,l1,g0,p4,t0,i4,+4,c1,(0,W4

au FileType haskell,cabal,python,sql,sh setlocal expandtab
au FileType haskell,cabal,python,sql,sh setlocal tabstop=4
au FileType haskell,cabal,python,sql,sh setlocal shiftwidth=4
au FileType haskell,cabal,python,sql,sh setlocal softtabstop=4

au FileType xml,xsl,html,js,css,sass,scheme setlocal expandtab
au FileType xml,xsl,html,js,css,sass,scheme setlocal tabstop=2
au FileType xml,xsl,html,js,css,sass,scheme setlocal shiftwidth=2
au FileType xml,xsl,html,js,css,sass,scheme setlocal softtabstop=2
au FileType xml,xsl,html,js,css,sass,scheme setlocal textwidth=500

au FileType mail setlocal spell
au FileType mail source ~/.vim/scripts/mutt.vim

au FileType git setlocal spell

source ~/.vim/local.vim
