syntax on
colorscheme desert256
filetype plugin indent on

set fileencodings=utf8,cp1251

set autoindent
set background=dark
set backspace=indent,eol,start
set cindent
set cinoptions=:0,l1,g0,p4,t0,i4,+4,c1,(0,W4
set clipboard^=unnamed
set formatoptions+=tqcro
set hidden
set ignorecase
set incsearch
set lazyredraw
set modeline
set mouse=a
set nobackup
set nocompatible
set noerrorbells
set noexpandtab
set nohlsearch
set noshowmatch
set noerrorbells
set visualbell
set nowrap
set pastetoggle=<f12>
set ruler
set scrolloff=3
set showcmd
set showmode
set smartcase
set smartindent
set smarttab
set spelllang=en,ru
set t_vb=
set textwidth=78
set ttyfast

let g:miniBufExplMapWindowNavVim=1 
let g:miniBufExplMapWindowNavArrows=1 
let g:miniBufExplMapCTabSwitchBufs=1 
let g:miniBufExplModSelTarget=1 
let g:miniBufExplMapCTabSwitchBufs=1
let g:miniBufExplUseSingleClick=1
let g:miniBufExplCloseOnSelect=1
let g:miniBufExplorerMoreThanOne=1000

map  <silent> <F11> :set spell!<CR>
map! <silent> <F11> <ESC>:set spell!<CR>i

nmap <silent> <C-D> :NERDTreeToggle \| :silent NERDTreeMirror<CR>
map! <silent> <C-D> <ESC>:NERDTreeToggle \| :silent NERDTreeMirror<CR>

nmap <silent> <C-B> :MiniBufExplorer<CR>
map! <silent> <C-B> <ESC>:MiniBufExplorer<CR>

au FileType xml,xsl,html,js,css,sass setlocal expandtab
au FileType xml,xsl,html,js,css,sass setlocal tabstop=2
au FileType xml,xsl,html,js,css,sass setlocal shiftwidth=2
au FileType xml,xsl,html,js,css,sass setlocal softtabstop=2
au FileType xml,xsl,html,js,css,sass setlocal textwidth=500

au FileType haskell,cabal,python,sql setlocal expandtab
au FileType haskell,cabal,python,sql setlocal tabstop=4
au FileType haskell,cabal,python,sql setlocal shiftwidth=4
au FileType haskell,cabal,python,sql setlocal softtabstop=4

au FileType makefile setlocal noexpandtab
au FileType makefile setlocal tabstop=8
au FileType makefile setlocal shiftwidth=8
au FileType makefile setlocal softtabstop=8

au FileType mail setlocal spell
au FileType mail source ~/.vim/scripts/mutt.vim

au BufNewFile,BufRead COMMIT_EDITMSG setlocal filetype=conf
au BufNewFile,BufRead COMMIT_EDITMSG setlocal spell

source ~/.vim/local.vim
