#!/usr/bin/env python

import os.path
import imaplib
import time
import imp

while True:
    try:
        config = imp.load_source('config', os.path.expanduser("~/.config/imap-unseen.conf"))

        server = imaplib.IMAP4_SSL(config.mailserver, config.port)
        server.login(config.username, config.password)
        server.select(config.mailbox)

        connected = True
        while connected:
            try:
                data = str(server.status(config.mailbox, '(UNSEEN)'))
                tokens = data.split()
                count = int(tokens[3].partition(')')[0])
                if count > 0:
                    print ('M:%d') % count
                else:
                    print ''

                time.sleep(10)

            except:
                connected = False

        server.close()
        server.logout()

    except:
        print 'FAIL'

    time.sleep(1)
