#!/bin/sh

xrandr -s 0

xsetroot -solid '#4c4d4e'
xsetroot -cursor_name left_ptr

xrdb ~/.Xresources

feh --bg-center ~/.wallpaper

urxvtd -q -o >/dev/null 2>&1 &
xset b off >/dev/null 2>&1 &

[ -x /usr/bin/xscreensaver ] && xscreensaver >/dev/null 2>&1 &
trayer --edge top --align right --widthtype pixel --width 72 --height 18 --margin 171 --tint 0x6c6d6e --transparent true --alpha 0 >/dev/null 2>&1 &

if [ -f $HOME/.xinitrc.local ]; then
    . $HOME/.xinitrc.local
fi

dbus-launch --exit-with-session xmonad >/dev/null 2>&1
