[ -z "$PS1" ] && return

export PATH=$HOME/local/bin:$HOME/.cabal/bin:/sbin:/usr/sbin:/usr/local/sbin:$PATH
export LC_CTYPE=ru_RU.UTF-8
export LC_COLLATE=ru_RU.UTF-8
export LC_PAPER=ru_RU.UTF-8
export LC_MEASUREMENT=ru_RU.UTF-8
export EDITOR=vim
export VISUAL=$EDITOR
export PAGER=less
export BC_ENV_ARGS="-q $HOME/.bcrc"
export _JAVA_AWT_WM_NONREPARENTING=1

if [ `tty` = "/dev/tty1" ]; then
    startx
    exit
fi

HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

shopt -s histappend
shopt -s checkwinsize

set -o vi
setterm -blength 0

[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

PS1='\u@\H\$ '

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\u@\H: \w\a\]$PS1"
    ;;
*)
    ;;
esac

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

if [ -f $HOME/.bashrc.local ]; then
    . $HOME/.bashrc.local
fi
